FROM golang:latest AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /consumer ./cmd/consumer

FROM alpine:latest
COPY --from=builder /consumer /consumer
CMD ["/consumer"]
